stages:
  - test

merge:
  image: alpine:edge
  stage: test
  script:
    - apk update
    - apk add alpine-sdk cmake openssl-dev
    - CXXFLAGS=-Werror cmake -DCMAKE_BUILD_TYPE=Debug .
    - make | tee make.log
    - CTEST_OUTPUT_ON_FAILURE=1 ctest | tee test.log
  only:
    - merge_requests
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ./*.log

